source 'https://rubygems.org'

gem 'rails', '3.2.2'

gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>=1.0.3'
  gem 'yui-compressor'
  gem 'execjs'
  gem 'therubyracer'
end
# UI

## jquery rails library
gem 'jquery-rails'

## Twitter Bootstrap for Sass
gem 'bootstrap-sass', '~> 2.0.1'

## HTML format
gem 'slim'

## Pagination
gem 'kaminari'

## Views - https://github.com/jcasimir/draper
gem 'draper'

# Backend

## time stamps
gem 'stamp' # https://github.com/jeremyw/stamp

## money / currency conversions
gem 'money'

## Add tags
gem "acts-as-taggable-on", "~> 2.1.0"

## Authentication: Added devise authentication to integrate users
#gem 'devise'
#gem 'omniauth-facebook'
#gem 'omniauth-github', :git => 'git://github.com/intridea/omniauth-github.git'
#gem 'omniauth-google'

# Metrics
## Logging useful metrics in production
gem 'newrelic_rpm'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Deploy with Capistrano
# gem 'capistrano'

group :development, :test do

  # test models and controllers
  gem 'rspec-rails'

  # integration tests
  gem 'cucumber-rails'

  # for javascript annotations
  gem 'capybara'

  # to use save_and_open_page
  gem 'launchy'

  # automagically run tests
  gem 'autotest-rails'

  # clean database quickly
  gem 'database_cleaner'

  # Keep a rails test environment in memory allow rspec to fork
  gem 'spork'

  # colors for the terminal
  gem 'term-ansicolor'

  # Pretty printed test output
  gem 'turn', :require => false

  # gem 'redgreen', :require => false

  if RUBY_PLATFORM =~ /darwin/i
    gem 'autotest-growl'
    gem 'autotest-fsevent'
  end

  # Data faker
  gem 'faker'

end

group :development do

  gem 'annotate', :git => 'git://github.com/ctran/annotate_models.git'

  # manage vendor assets
  gem 'vendorer' # https://github.com/grosser/vendorer

  # Simple SMTP server and mail viewer
  gem 'mailcatcher'

  # Development database
  gem 'sqlite3'

  # For Debugging
  gem 'pry-rails'

  # Hirb - Better viewing of structured data
  gem 'hirb'

  # Pretty Printing
  gem 'awesome_print'

  # Analysis and best practices
  gem 'rails_best_practices'
end

group :test do
  # To use debugger
  # gem 'ruby-debug19', :require => 'ruby-debug'

  # Test coverage
  gem "simplecov", :require => false

  # shoulda
  gem "shoulda", "3.0.1"
end


group :production do

  # production database
  gem 'mysql'

  # syncing assets to s3 / rackspace
  gem 'asset_sync'

  # notification of errors
  gem 'hoptoad_notifier'
end
